"""11

Revision ID: 20260727133156
Revises: 20260727124537
Create Date: 2026-07-27 13:31:58.395519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260727133156'
down_revision: Union[str, Sequence[str], None] = '20260727124537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_players', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_players', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
