"""8

Revision ID: 20260725182611
Revises: 20260507101855
Create Date: 2026-07-25 18:26:14.589555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260725182611'
down_revision: Union[str, Sequence[str], None] = '20260507101855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('game_players_player_id_game_id_key'), 'game_players', type_='unique')
    op.add_column('games', sa.Column('poll', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('table_players_table_id_player_id_key'), 'table_players', type_='unique')
    op.drop_constraint(op.f('tables_game_id_number_round_key'), 'tables', type_='unique')
    op.drop_column('tables', 'round')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tables_game_id_number_round_key'), 'tables', ['game_id', 'number', 'round'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('table_players_table_id_player_id_key'), 'table_players', ['table_id', 'player_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('games', 'poll')
    op.create_unique_constraint(op.f('game_players_player_id_game_id_key'), 'game_players', ['player_id', 'game_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
