"""12

Revision ID: 20260727164212
Revises: 20260727133156
Create Date: 2026-07-27 16:42:16.012389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260727164212'
down_revision: Union[str, Sequence[str], None] = '20260727133156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chats', sa.Column('message_with_tables_id', sa.BigInteger(), nullable=True))
    op.add_column('telegram_chats', sa.Column('message_with_tables', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_chats', 'message_with_tables')
    op.drop_column('telegram_chats', 'message_with_tables_id')
    # ### end Alembic commands ###
