"""9

Revision ID: 20260726173627
Revises: 20260725182611
Create Date: 2026-07-26 17:36:32.129580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260726173627'
down_revision: Union[str, Sequence[str], None] = '20260725182611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('poll_id', sa.String(), nullable=True))
    op.drop_column('games', 'poll')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('poll', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('games', 'poll_id')
    # ### end Alembic commands ###
