"""13

Revision ID: 20260729155206
Revises: 20260727164212
Create Date: 2026-07-29 15:52:08.825855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260729155206'
down_revision: Union[str, Sequence[str], None] = '20260727164212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('poll_register_id', sa.String(), nullable=True))
    op.add_column('games', sa.Column('poll_exit_id', sa.String(), nullable=True))
    op.add_column('games', sa.Column('registered', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'registered')
    op.drop_column('games', 'poll_exit_id')
    op.drop_column('games', 'poll_register_id')
    # ### end Alembic commands ###
