"""10

Revision ID: 20260727124537
Revises: 20260726173627
Create Date: 2026-07-27 12:45:40.189840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260727124537'
down_revision: Union[str, Sequence[str], None] = '20260726173627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('elo_change_per_match', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'elo_change_per_match')
    # ### end Alembic commands ###
